### ISSUE TITLE
Feature: Slides should be deployed live

### ISSUE THREAD

**Issue by jeseekia** [girldevelopit/gdi-python#6]
Use a gh-pages deployment

**Comment by pamelafox** [comment]
Gh-pages is already on, at https://girldevelopit.github.io/gdi-python/ ?
(That's what I used with students)
Or something fancier?

**Comment by jeseekia** [comment]
I see. For some reason it really wasn't showing up for me under the settings right. Or maybe I was subconsciously looking for the old school gh-pages branch setup. 😅
